// <auto-generated />
#nullable enable

[assembly: global::System.Reflection.AssemblyMetadata("AtomUILanguageModuleId", "IconParkGallery")]

namespace AtomUI.Generated.IconParkGallery
{
    internal static class GeneratedLanguageModuleRegistration
    {
        internal static void Register(global::AtomUI.Localization.ILocalizationBuilder builder)
        {
            global::System.ArgumentNullException.ThrowIfNull(builder);
            global::AtomUI.Generated.IconParkGallery.GeneratedLanguageCatalog_23C98AB184BB4F52.Register(builder);
            global::AtomUI.Generated.IconParkGallery.GeneratedLanguageCatalog_13A91BA609C4EA8D.Register(builder);
        }
    }
}
