// <auto-generated />
#nullable enable

namespace IconParkGallery.Localization
{
    public sealed class NavigationLangResourceExtension
        : global::AtomUI.Localization.LanguageResourceExtension<global::IconParkGallery.Localization.NavigationLangResourceKind>
    {
        public NavigationLangResourceExtension()
        {
        }

        public NavigationLangResourceExtension(
            global::IconParkGallery.Localization.NavigationLangResourceKind kind)
            : base(kind)
        {
        }
    }
}
