// <auto-generated />
#nullable enable

namespace AtomUI.Generated.IconParkGallery
{
    internal static class GeneratedLanguageCatalog_13A91BA609C4EA8D
    {
        internal static void Register(global::AtomUI.Localization.ILocalizationBuilder builder)
        {
            global::System.ArgumentNullException.ThrowIfNull(builder);
            builder.AddCatalog(
                new global::AtomUI.Localization.LanguageCatalogDescriptor<global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind>(
                    "IconParkGallery:IconParkGallery.Localization.WorkspaceWindowLangResourceKind",
                    2,
                    new global::AtomUI.Localization.LanguageCatalogUnitDescriptor[]
                    {
                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor("MenuItemAppearance", false),
                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor("MenuItemCompactMode", false),
                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor("MenuItemDarkMode", false),
                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor("MenuItemEnableFullScreen", false),
                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor("MenuItemEnableMaximize", false),
                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor("MenuItemEnableMinimize", false),
                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor("MenuItemEnableMotion", false),
                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor("MenuItemEnableMove", false),
                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor("MenuItemEnablePin", false),
                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor("MenuItemEnableResize", false),
                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor("MenuItemEnableWaveSpirit", false),
                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor("MenuItemFollowSystem", false),
                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor("MenuItemLanguage", false),
                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor("MenuItemLightMode", false),
                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor("MenuItemSettings", false),
                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor("MenuItemTheme", false),
                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor("MenuItemThemeSettings", false),
                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor("MenuItemWindowOptions", false),
                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor("WindowTitle", false),
                    },
                    static kind => kind switch
                    {
                        global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind.MenuItemAppearance => 0,
                        global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind.MenuItemCompactMode => 1,
                        global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind.MenuItemDarkMode => 2,
                        global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind.MenuItemEnableFullScreen => 3,
                        global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind.MenuItemEnableMaximize => 4,
                        global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind.MenuItemEnableMinimize => 5,
                        global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind.MenuItemEnableMotion => 6,
                        global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind.MenuItemEnableMove => 7,
                        global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind.MenuItemEnablePin => 8,
                        global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind.MenuItemEnableResize => 9,
                        global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind.MenuItemEnableWaveSpirit => 10,
                        global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind.MenuItemFollowSystem => 11,
                        global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind.MenuItemLanguage => 12,
                        global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind.MenuItemLightMode => 13,
                        global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind.MenuItemSettings => 14,
                        global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind.MenuItemTheme => 15,
                        global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind.MenuItemThemeSettings => 16,
                        global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind.MenuItemWindowOptions => 17,
                        global::IconParkGallery.Localization.WorkspaceWindowLangResourceKind.WindowTitle => 18,
                        _ => -1,
                    }));
            builder.AddTranslationBundle(
                new global::AtomUI.Localization.TranslationBundleDescriptor(
                    "IconParkGallery:IconParkGallery.Localization.WorkspaceWindowLangResourceKind",
                    2,
                    global::AtomUI.Localization.LanguageTag.Parse("en-US"),
                    global::AtomUI.Localization.TranslationSourceKind.ModuleBuiltIn,
                    "IconParkGallery",
                    new string?[]
                    {
                        "Appearance",
                        "Compact Mode",
                        "Dark Mode",
                        "Enable FullScreen",
                        "Enable Maximize",
                        "Enable Minimize",
                        "Enable Motion",
                        "Enable Move",
                        "Enable Pin",
                        "Enable Resize",
                        "Enable WaveSpirit",
                        "Follow System",
                        "Language",
                        "Light Mode",
                        "Settings",
                        "Theme",
                        "Theme Settings",
                        "Window Options",
                        "IconPark Icons Gallery",
                    }));
            builder.AddTranslationBundle(
                new global::AtomUI.Localization.TranslationBundleDescriptor(
                    "IconParkGallery:IconParkGallery.Localization.WorkspaceWindowLangResourceKind",
                    2,
                    global::AtomUI.Localization.LanguageTag.Parse("pt-BR"),
                    global::AtomUI.Localization.TranslationSourceKind.ModuleBuiltIn,
                    "IconParkGallery",
                    new string?[]
                    {
                        "Aparência",
                        "Modo compacto",
                        "Modo escuro",
                        "Ativar tela cheia",
                        "Ativar maximizar",
                        "Ativar minimizar",
                        "Ativar movimento",
                        "Ativar mover",
                        "Ativar fixar",
                        "Ativar redimensionar",
                        "Ativar WaveSpirit",
                        "Seguir sistema",
                        "Idioma",
                        "Modo claro",
                        "Configurações",
                        "Tema",
                        "Configurações de tema",
                        "Opções da janela",
                        "IconPark Icons Gallery",
                    }));
            builder.AddTranslationBundle(
                new global::AtomUI.Localization.TranslationBundleDescriptor(
                    "IconParkGallery:IconParkGallery.Localization.WorkspaceWindowLangResourceKind",
                    2,
                    global::AtomUI.Localization.LanguageTag.Parse("zh-CN"),
                    global::AtomUI.Localization.TranslationSourceKind.ModuleBuiltIn,
                    "IconParkGallery",
                    new string?[]
                    {
                        "外观模式",
                        "紧凑模式",
                        "暗黑模式",
                        "开启全屏",
                        "开启最大化",
                        "开启最小化",
                        "开启动效",
                        "开启窗口移动",
                        "开启窗口固定",
                        "开启窗口设置大小",
                        "开启波浪动画",
                        "跟随系统",
                        "语言",
                        "明亮模式",
                        "设置",
                        "主题",
                        "主题设置",
                        "窗口选项",
                        "IconPark 图标库",
                    }));
            builder.AddTranslationBundle(
                new global::AtomUI.Localization.TranslationBundleDescriptor(
                    "IconParkGallery:IconParkGallery.Localization.WorkspaceWindowLangResourceKind",
                    2,
                    global::AtomUI.Localization.LanguageTag.Parse("zh-TW"),
                    global::AtomUI.Localization.TranslationSourceKind.ModuleBuiltIn,
                    "IconParkGallery",
                    new string?[]
                    {
                        "外觀模式",
                        "緊湊模式",
                        "暗黑模式",
                        "開啓全屏",
                        "開啓最大化",
                        "開啓最小化",
                        "開啓動效",
                        "開啓窗口移動",
                        "開啓窗口固定",
                        "開啓窗口設置大小",
                        "開啓波浪動畫",
                        "跟隨系統",
                        "語言",
                        "明亮模式",
                        "設置",
                        "主題",
                        "主題設定",
                        "窗口選項",
                        "IconPark 圖標庫",
                    }));
        }
    }
}
