<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AtomUITargetFrameworks)</TargetFrameworks>
        <OutputType>WinExe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ApplicationIcon>Assets/IconParkGallery.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <TrimmerRootDescriptor Include="Roots.xml"/>
    </ItemGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <!--        <IsTrimmable>true</IsTrimmable>-->
        <!--        <PublishTrimmed>true</PublishTrimmed>-->
        <!--        <PublishAot>true</PublishAot>-->
        <UseAppHost>true</UseAppHost>
    </PropertyGroup>

    <PropertyGroup>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop"/>
        <ProjectReference Include="../IconParkGallery/IconParkGallery.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="Assets/Images/IconParkGallery.ico">
            <Link>IconParkGallery.ico</Link>
        </None>
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Remove="Assets/IconParkGallery.ico" />
    </ItemGroup>
</Project>
