// <auto-generated />
namespace AtomUI.Generated.IconParkGallery;

internal static class GeneratedControlThemeAssetManifest
{
    internal static global::System.Collections.Generic.IReadOnlyList<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor> GetDescriptors()
    {
        return new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor[]
        {
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://IconParkGallery/Controls/IconGallery/Themes/IconGalleryTheme.axaml"), new global::AtomUI.Theme.Schema.ControlTokenIdentity("IconParkGallery", "IconGallery"), new global::AtomUI.Theme.Schema.ControlTokenIdentity[] { new global::AtomUI.Theme.Schema.ControlTokenIdentity("IconParkGallery", "IconGallery"), }, null, 0x23A71B19E75305A3UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://IconParkGallery/Controls/IconGallery/Themes/IconInfoItemTheme.axaml"), new global::AtomUI.Theme.Schema.ControlTokenIdentity("IconParkGallery", "IconInfoItem"), new global::AtomUI.Theme.Schema.ControlTokenIdentity[] { new global::AtomUI.Theme.Schema.ControlTokenIdentity("IconParkGallery", "IconGallery"), new global::AtomUI.Theme.Schema.ControlTokenIdentity("IconParkGallery", "IconInfoItem"), }, null, 0x6C5C94514F0DB51BUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://IconParkGallery/Controls/Navigation/Themes/NavigationTheme.axaml"), new global::AtomUI.Theme.Schema.ControlTokenIdentity("IconParkGallery", "Navigation"), new global::AtomUI.Theme.Schema.ControlTokenIdentity[] { new global::AtomUI.Theme.Schema.ControlTokenIdentity("IconParkGallery", "Navigation"), }, null, 0x1C29DD81CA862735UL),
        };
    }
}

internal static class GeneratedControlThemeAssetResources
{
    internal static void AddResources(
        global::AtomUI.Theme.Resources.IControlThemesProvider provider,
        global::System.Collections.Generic.IReadOnlyList<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor> assets)
    {
        global::System.ArgumentNullException.ThrowIfNull(provider);
        global::System.ArgumentNullException.ThrowIfNull(assets);
        var controlThemes = provider.ControlThemes;
        foreach (var asset in assets)
        {
            switch (asset.AssetUri.AbsoluteUri)
            {
                case "avares://IconParkGallery/Controls/IconGallery/Themes/IconGalleryTheme.axaml":
                {
                    controlThemes.Add(new GeneratedThemeAssetResource_351A71D20105E548());
                    break;
                }
                case "avares://IconParkGallery/Controls/IconGallery/Themes/IconInfoItemTheme.axaml":
                {
                    controlThemes.Add(new GeneratedThemeAssetResource_3929B5E93B9D9E8B());
                    break;
                }
                case "avares://IconParkGallery/Controls/Navigation/Themes/NavigationTheme.axaml":
                {
                    controlThemes.Add(new GeneratedThemeAssetResource_47807A8CB892D152());
                    break;
                }
            }
        }
    }
}
